In [1]:
from numpy import *

In [1]:
import numpy as np
l1=[1,2,3,4]
n1=np.array(l1)
print(n1)
type(n1)

[1 2 3 4]


numpy.ndarray

In [3]:
l1=[1,2,3]
n1 = array(l1)
print(n1)

[1 2 3]


In [4]:
type(n1)

numpy.ndarray

In [9]:
l1=array([1,2,3,4,5.0])       #sb ka data type float krdiya becoz ek float tha baki sare int me.
print(l1.dtype)
print(l1)

float64
[1. 2. 3. 4. 5.]


In [8]:
l1=array([1,2,3,4,5],float)       #sb ka data type float krdiya
print(l1.dtype)
print(l1)          

float64
[1. 2. 3. 4. 5.]


In [19]:
#l1=linspace(start,stop,part)

l1=linspace(0,15)
print(l1.dtype)
print(l1)          

float64
[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [20]:
l1=linspace(0,10,20)
print(l1.dtype)
print(l1)    

float64
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [24]:
#arange(1st_elemnet,last_element,step)

l1=arange(0,50,3)
print(l1.dtype)
print(l1)    

int32
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [6]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
l1=arange(0,10,2)
print(l1.dtype)
print(l1)

int32
[0 2 4 6 8]


In [26]:
#logspae(log1 base10, log40 base10, 5parts me divide honge log ke values)

l1=logspace(1,40,5)
print(l1.dtype)
print(l1)

float64
[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [27]:
l1=logspace(1,40)
print(l1.dtype)
print(l1)

float64
[1.00000000e+01 6.25055193e+01 3.90693994e+02 2.44205309e+03
 1.52641797e+04 9.54095476e+04 5.96362332e+05 3.72759372e+06
 2.32995181e+07 1.45634848e+08 9.10298178e+08 5.68986603e+09
 3.55648031e+10 2.22299648e+11 1.38949549e+12 8.68511374e+12
 5.42867544e+13 3.39322177e+14 2.12095089e+15 1.32571137e+16
 8.28642773e+16 5.17947468e+17 3.23745754e+18 2.02358965e+19
 1.26485522e+20 7.90604321e+20 4.94171336e+21 3.08884360e+22
 1.93069773e+23 1.20679264e+24 7.54312006e+24 4.71486636e+25
 2.94705170e+26 1.84206997e+27 1.15139540e+28 7.19685673e+28
 4.49843267e+29 2.81176870e+30 1.75751062e+31 1.09854114e+32
 6.86648845e+32 4.29193426e+33 2.68269580e+34 1.67683294e+35
 1.04811313e+36 6.55128557e+36 4.09491506e+37 2.55954792e+38
 1.59985872e+39 1.00000000e+40]


In [28]:
#zeros()

l1=zeros(10)
print(l1.dtype)
print(l1)

float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
import numpy as np
n1=np.zeros((2,3),int)        #2rows&3column
print(n1)

[[0 0 0]
 [0 0 0]]


In [29]:
l1=zeros(10,int)
print(l1.dtype)
print(l1)

int32
[0 0 0 0 0 0 0 0 0 0]


In [31]:
#ones()
l1=ones(10)
print(l1.dtype)
print(l1)

float64
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [32]:
#ones()
l1=ones(10,int)
print(l1.dtype)
print(l1)

int32
[1 1 1 1 1 1 1 1 1 1]


In [6]:
import numpy as np
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
print(z)

z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#BASIC OPERATIONS

In [41]:
arr = array([1,2,3,4,5])
arr=arr+5
print(arr)

[ 6  7  8  9 10]


In [30]:
from numpy import *

In [31]:
arr = array([10,20,30,40,50])
arr=arr-5
print(arr)

[ 5 15 25 35 45]


In [32]:
arr = array([1,2,3,4,5])
arr=arr*2
print(arr)

[ 2  4  6  8 10]


In [39]:
arr = array([10,20,30,40])
arr=arr/2
print(arr)

[ 5. 10. 15. 20.]


In [42]:
#VECTORIZED OPERATION
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,10])
arr3=arr1+arr2
print(arr3)

[ 7  9 11 13 15]


In [46]:
arr = array([1,2,3,4,5])
print(sin(arr))
print(cos(arr))
print(log(arr))
print(sum(arr))  #ADDITION
print(sqrt(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
15
[1.         1.41421356 1.73205081 2.         2.23606798]


In [27]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n1,n2])

100

In [40]:
from numpy import *

In [43]:
n1 = random.randint(1,50,10)
n1

array([ 4, 16, 18, 25, 40, 22,  3, 20, 44, 38])

In [44]:
#MEAN
mean(n1)

23.0

In [45]:
#MEDIAN
median(n1)

21.0

In [46]:
#STANDARD DEVIATION
std(n1)

13.431306712304652

In [28]:
#COLUMN ELEMNETS ADDITION
np.sum([n1,n2],axis=0)

array([40, 60])

In [29]:
#ROW ELEMNET ADDITION
np.sum([n1,n2],axis=1)

array([30, 70])

In [49]:
#concatenate no. of brackets ka dhyan rkhe.
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,10])
print(concatenate([arr2,arr1]))

[ 6  7  8  9 10  1  2  3  4  5]


In [19]:
import numpy as np

In [20]:
#HORIZONTAL STACK
n1=np.array([10,20,30])
n2=np.array([100,200,300])
np.hstack((n1,n2))

array([ 10,  20,  30, 100, 200, 300])

In [21]:
#VERTICAL STACK
n1=np.array([10,20,30])
n2=np.array([100,200,300])
np.vstack((n1,n2))

array([[ 10,  20,  30],
       [100, 200, 300]])

In [22]:
#COLUMN STACK
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

## Copying an Array

#### Shallow copy

In [51]:
arr1=array([1,2,3,4,5])
arr2=arr1
print(arr2)

[1 2 3 4 5]


In [52]:
print(id(arr1))
print(id(arr2))

1919178044080
1919178044080


In [53]:
arr1=array([1,2,3,4,5])
arr2=arr1.view()
print(arr2)
print(id(arr1))
print(id(arr2))

[1 2 3 4 5]
1919178046480
1919177958944


In [54]:
arr1=array([1,2,3,4,5])
arr2=arr1.view()

arr1[2]=99

print(arr2)
print(arr1)
print(id(arr1))
print(id(arr2))

[ 1  2 99  4  5]
[ 1  2 99  4  5]
1919177139344
1919178045200


In [55]:
arr1=array([1,2,3,4,5])
arr2=arr1

arr1[2]=99

print(arr2)
print(arr1)
print(id(arr1))
print(id(arr2))

[ 1  2 99  4  5]
[ 1  2 99  4  5]
1919177907616
1919177907616


#### Deep Copy

In [56]:
arr1=array([1,2,3,4,5])
arr2=arr1.copy()

arr1[2]=99

print(arr2)
print(arr1)
print(id(arr1))
print(id(arr2))

[1 2 3 4 5]
[ 1  2 99  4  5]
1919177082800
1919177926816


In [62]:
from numpy import *
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

print("A =", A) 
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row

column = [];        # empty list
for row in A:
  column.append(row[2])   

print("3rd column =", column)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[1] = [-5, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 12
3rd column = [5, 9, 11]


## Working with Matrix

In [57]:
from numpy import *

In [61]:
arr = array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [63]:
import numpy as np            

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)


[[ 36 -12]
 [ -1   2]]


In [11]:
arr = array([[1,2,3],[4,5,6]])
print(arr.ndim)       #ndim()- '2d' array btarha
print(arr.shape)      #no of rows & column ie 2rows & 3 column bs bta rha ha, returns a tuple()
print(arr.size)
print(arr)

2
(2, 3)
6
[[1 2 3]
 [4 5 6]]


In [12]:
arr.shape=(3,2)          #with "shape" we changed the shape from (2,3) to (3,2).
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [68]:
arr = array([[1,2,3],[4,5,6]])
arrA=arr.flatten()             #2D to 1D
print(arrA)

[1 2 3 4 5 6]


In [73]:
#1D to 2D
arr1=array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
arr2=arr1.flatten()
print(arr2)

[1 2 3 4 5 6 1 2 3 4 5 6]


In [74]:
arr3=arr2.reshape(3,4)
print(arr3)

[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]


In [ ]:
#3d

In [75]:
arr1=array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]
])
arr2=arr1.flatten()
arr3=arr2.reshape(2,2,3)
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [4]:
from numpy import *

In [5]:
#full() for creating array with specific nos.
n = full((4,4),99)       
print(n)

[[99 99 99 99]
 [99 99 99 99]
 [99 99 99 99]
 [99 99 99 99]]


In [8]:
random.randint(100,200,10)  #every time diff set of nos will come when run is pprssed

array([169, 198, 116, 131, 158, 133, 149, 180, 173, 103])

In [ ]:
#INTERSECTION & DIFFERENCE

In [23]:
import numpy as np

In [24]:
n1=np.array([10,20,30,40,50,60,70])
n2=np.array([50,60,70,80,90,100])
np.intersect1d(n1,n2)

array([50, 60, 70])

In [25]:
n1=np.array([10,20,30,40,50,60,70])
n2=np.array([50,60,70,80,90,100])
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [26]:
n1=np.array([10,20,30,40,50,60,70])
n2=np.array([50,60,70,80,90,100])
np.setdiff1d(n2,n1)

array([ 80,  90, 100])

In [ ]:
#SAVE & LOAD

In [47]:
from numpy import *

In [48]:
n1= array([1,2,3,4,5,6,7,8,9])
save("my_numpy",n1)

In [49]:
n2= load("my_numpy.npy")             # ".nyp" stands for numpy array
n2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Miscellaneous

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
type(a)

numpy.ndarray

In [3]:
a.dtype

dtype('int32')

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a[0]=99
a

array([99,  2,  3,  4])

In [6]:
a[0]=9.11
a

array([9, 2, 3, 4])

In [10]:
a.shape

(4,)

In [11]:
a.size #no of elements in array

4

In [12]:
a=np.array([[1,2,3,4],
            [8,7,6,5]])

In [13]:
a[1,3]

5

In [15]:
a[1,3]=-99
print(a)

[[  1   2   3   4]
 [  8   7   6 -99]]


In [16]:
a

array([[  1,   2,   3,   4],
       [  8,   7,   6, -99]])

In [17]:
a[1]

array([  8,   7,   6, -99])

#### SLICING

In [18]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a[1:3]

array([2, 3])

In [22]:
a[1:-2]

array([2, 3, 4, 5, 6, 7])

In [23]:
a[-4:3]

array([], dtype=int32)

#### OMITTING INDICES

In [24]:
a[:3]

array([1, 2, 3])

In [26]:
a[-3:]

array([7, 8, 9])

In [28]:
a[::4]      #GIVING EVERY 4TH ELEMENT

array([1, 5, 9])

In [6]:
a=np.array([[0,1,2,3,4,5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           ])

In [7]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [8]:
a[0,3:5]

array([3, 4])

In [9]:
a[2: ,3: ]

array([[23, 24, 25],
       [33, 34, 35]])

In [10]:
a[:,2]      #from all the rows give me only the 2nd column #default representation 1d me hoga

array([ 2, 12, 22, 32])

In [41]:
a[1::2, ::3]

array([[10, 13],
       [30, 33]])

In [47]:
a=np.arange(25).reshape(5,5)

In [48]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
a[:,1:4:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [53]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [52]:
a[-1,:]

array([20, 21, 22, 23, 24])

In [54]:
a[4,:]

array([20, 21, 22, 23, 24])

In [57]:
a[1:4:2,0:3:2]

array([[ 5,  7],
       [15, 17]])

### FANCY INDEXING

In [4]:
p = np.arange(0,80,10)
p

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [6]:
indices = [1,2,-3]
y  = p[indices]
print(y)

[10 20 50]


In [7]:
## CHANGE USING FANCY

In [8]:
p[indices] = 9999

In [9]:
p

array([   0, 9999, 9999,   30,   40, 9999,   60,   70])

In [3]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [3]:
np1=np.array([1,2,3,4])
np1

array([1, 2, 3, 4])

In [5]:
np2=np.full((4,4),99)
np2

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])