In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

1

In [6]:
a.shape

(5,)

In [7]:
a.size

5

In [10]:
f =np.array([11.5,12.5,13.5,44.5,55.7])

In [11]:
a+f

array([12.5, 14.5, 16.5, 48.5, 60.7])

In [12]:
a*10

array([10, 20, 30, 40, 50])

In [19]:
#np.sin(a)
#np.cos(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [36]:
a=np.array([[0,1,2,3,4,5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]
           ])

In [37]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [38]:
a[0:2,0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [42]:
a[2::2 , ::2 ]

array([[20, 22, 24],
       [40, 42, 44]])

In [53]:
z = np.arange(25).reshape(5,5)
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
z[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [57]:
z[4,:]

array([20, 21, 22, 23, 24])

In [59]:
z[1:4:2 , 0:3:2]

array([[ 5,  7],
       [15, 17]])

In [68]:
p = np.arange(0,80,10)
p

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [69]:
indices = [1,2,-1]
y  = p[indices]
print(y)

[10 20 70]


In [70]:
y

array([10, 20, 70])